---

- name: Install dependencies on ArchLinux
  package:
    name: "{{ package_item }}"
    state: present
  become: yes
  with_items:
    - fakeroot
    - fuse2
    - gcc
    - git
    - acl
    - lz4
    - openssl
    - patch
    - pkg-config
    - python
  loop_control:
    loop_var: package_item
