---

- name: Install dependencies on Debian-based distributions
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - fakeroot
    - fuse
    - git
    - libacl1-dev
    - libfuse-dev
    - liblz4-dev
    - libssl-dev
    - pkg-config
    - python3-dev
    - python3-pip
    - python3-setuptools
  become: yes
