---

- name: Include OS-specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
  become: 'yes'

- name: Install python pip
  easy_install:
    name: pip
    state: present
  become: 'yes'

- name: Install python virtualenv
  pip:
    name: virtualenv
    state: present

- name: Install borgbackup using pip and virtualenv
  pip:
    name: borgbackup
    version: "{{ borg_backup_version }}"
    state: present
    virtualenv: /opt/borg_backup
  become: 'yes'

- name: Symlink borgbackup
  file:
    src: /opt/borg_backup/bin/borg
    dest: /usr/local/bin/borg
    state: link
  become: yes
