---

- name: Include OS-specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
  become: 'yes'

- name: Install python pip
  easy_install:
    name: pip
    state: present

- name: Install python virtualenv
  pip:
    name: virtualenv
    state: present

  #- name: Install borg_backup using pip
  #  pip:
  #    name: borg_backup
  #    version: "{{ borg_backup_version }}"
  #    state: present
  #    executable: pip3
  #  become: 'yes'
